### ISSUE TITLE
Consider not base64 encoding payloads in the log files

### ISSUE THREAD

**Issue by FX-HAO** [rabbitmq/rabbitmq-tracing#23]
So that we can directly see the published payload without manual decoding.

**Comment by michaelklishin** [comment]
This plugin encodes values before logging them. It could also not do that, I'm not 100% sure on the reasons to do so as they go back years. Payload can contain characters that can make the JSON output invalid or otherwise unsafe for logging.

This plugin is a matter of developer convenience. Nothing prevents you from developing a similar tool with [little effort](http://www.rabbitmq.com/firehose.html). So I suggest that you do that instead.
