### ISSUE TITLE
add a tracing auth_failure,"Refused"

### ISSUE THREAD

**Issue by letiscoding** [rabbitmq/rabbitmq-tracing#26]
1.docker pull rabbitmq
2.docker run --privileged=true -d --restart=always \
 --hostname rabbit -e RABBITMQ_DEFAULT_USER=root -e RABBITMQ_DEFAULT_PASS=rabbitpwd  \
 -d \
 -p 5671:5671 -p 5672:5672 -p 4369:4369  -p 15672:15672 -p 15671:15671  -p 25672:25672  \
 -v /data/rabbitmq-conf:/etc/rabbitmq \
 -v /data/rabbitmq-config:/var/lib/rabbitmq \
  --name rabbitmq rabbitmq 
3.
   rabbitmq-plugins enable rabbitmq_management \
  rabbitmq-plugins enable rabbitmq_tracing
4.web managerment  add a tracing:
       enter "text" and add 
5.the question
   **2018-08-22 09:30:08.628 [error] <0.19994.0> Supervisor {<0.19994.0>,rabbit_tracing_consumer_sup} had child consumer started with rabbit_tracing_consumer:start_link([{vhost,<<"/">>},{name,<<"test">>},{format,<<"text">>},{pattern,<<"#">>},{<<"format">>,<<"text">>},...]) at undefined exit with reason no match of right hand value {error,{auth_failure,"Refused"}} in rabbit_tracing_consumer:init/1 line 58 in context start_error**
please help,who can tell me then question?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
I cannot reproduce. Somehow the user used to add a trace consumer is refused access to the virtual host in question. Consider [granting that user the permissions](http://www.rabbitmq.com/access-control.html) (but I didn't have to do it in my test and only provided a trace file name).

**Comment by letiscoding** [comment]
think you very much,i will send mail to rabbitmq-users.thank you agen.

**Comment by shooding** [comment]
@letiscoding 

from log 
```
rabbit_tracing_consumer_sup} had child consumer started with rabbit_tracing_consumer:start_link...
"Refused"}} in rabbit_tracing_consumer:init/1 line 61...
```

When you Add a new trace, your need to set tracer connection username and password.
I found it working after setting these two params.
