### ISSUE TITLE
No "Tracing" tab shown

### ISSUE THREAD

**Issue by AntonTrapp** [rabbitmq/rabbitmq-tracing#34]
Hi!

Have a problem with this plugin.

> This plugin ships with RabbitMQ.
yes, shows in list
> Enabled it with rabbitmq-plugins enable
yes, get a nice log entry that it's enabled for the given vhost
> then see a "Tracing" tab in the management UI.
nope (except that it's hidden in white text on white ground, ...)

Plugin shows enabled in the plugin list.
Versions are: RabbitMQ 3.6.10 / Erlang 20.2.2
OS: Linux Mint (based on ubuntu 18.04.1)
Server logs: no errors/warnings, when enabling tracing it shows a text, that tracing has been enabled for the dev vhost.

Report (with trace related stuff):
`         rabbit_event,lists,queue,priority_queue,rabbit_router,rabbit_trace,
      {trace_vhosts,[<<"dev">>]},
amq.rabbitmq.trace	topic	true	false	true	[]	
amq.rabbitmq.trace	topic	true	false	true	[]	
`
Restarting rabbit (+ re-enabling tracing) does not change anything. Is this broken or is something missing in the documentation to get that tab?

**Comment by lukebakken** [comment]
Hello and thank you for using RabbitMQ.

Please post this question to the [`rabbitmq-users`](https://groups.google.com/forum/#!forum/rabbitmq-users) mailing list. You've included some of the necessary information to help us diagnose this issue, but we need more to be able to help:

* Provide a transcript of how you enabled the `rabbitmq_tracing` plugin.
* Provide the output of `rabbitmq-plugins list`. It is important to show command output rather than make statements about the plugin.
* Provide the exact text from the log file when the tracing is enabled.

Please note that you are using an unsupported version of RabbitMQ as well. I suggest re-trying using the latest version (`3.8.2` or `3.7.23`).
